const ciudades = [
  // MONTEVIDEO
  "Montevideo — Aguada",
  "Montevideo — Aire Puro",
  "Montevideo — Arroyo Seco",
  "Montevideo — Atahualpa",
  "Montevideo — Brazo Oriental",
  "Montevideo — Buceo",
  "Montevideo — Capurro",
  "Montevideo — Carrasco",
  "Montevideo — Carrasco Norte",
  "Montevideo — Casabó",
  "Montevideo — Casavalle",
  "Montevideo — Centro",
  "Montevideo — Cerrito de la Victoria",
  "Montevideo — Cerro",
  "Montevideo — Ciudad Vieja",
  "Montevideo — Colón",
  "Montevideo — Conciliación",
  "Montevideo — Cordón",
  "Montevideo — Flor de Maroñas",
  "Montevideo — Goes",
  "Montevideo — Jardines del Hipódromo",
  "Montevideo — La Blanqueada",
  "Montevideo — La Comercial",
  "Montevideo — La Figurita",
  "Montevideo — La Teja",
  "Montevideo — La Unión",
  "Montevideo — Las Canteras",
  "Montevideo — Larrañaga",
  "Montevideo — Lecocq",
  "Montevideo — Lezica",
  "Montevideo — Malvín",
  "Montevideo — Malvín Norte",
  "Montevideo — Manga",
  "Montevideo — Maroñas",
  "Montevideo — Mercado Modelo",
  "Montevideo — Miguelete",
  "Montevideo — Montevideo Viejo",
  "Montevideo — Nuevo París",
  "Montevideo — Palermo",
  "Montevideo — Parque Batlle",
  "Montevideo — Parque Bellán",
  "Montevideo — Parque Posadas",
  "Montevideo — Parque Rodó",
  "Montevideo — Paso de la Arena",
  "Montevideo — Paso de las Duranas",
  "Montevideo — Peñarol",
  "Montevideo — Piedras Blancas",
  "Montevideo — Pocitos",
  "Montevideo — Pocitos Nuevo",
  "Montevideo — Prado",
  "Montevideo — Punta Carretas",
  "Montevideo — Punta Gorda",
  "Montevideo — Reducto",
  "Montevideo — Retiro",
  "Montevideo — Sayago",
  "Montevideo — Shangrilá",
  "Montevideo — Tres Cruces",
  "Montevideo — Tres Ombúes",
  "Montevideo — Unión",
  "Montevideo — Villa Española",
  "Montevideo — Villa García",
  "Montevideo — Villa Muñoz",
  "Montevideo — Villa Dolores",
  "Montevideo — Jacinto Vera",

  // CANELONES
  "Canelones — Atlántida",
  "Canelones — Barros Blancos",
  "Canelones — Canelones ciudad",
  "Canelones — Ciudad de la Costa",
  "Canelones — Ciudad del Plata",
  "Canelones — El Pinar",
  "Canelones — Empalme Olmos",
  "Canelones — Jardines de Atlántida",
  "Canelones — Juan Antonio Artigas",
  "Canelones — Juanicó",
  "Canelones — La Floresta",
  "Canelones — La Paz",
  "Canelones — Las Piedras",
  "Canelones — Las Toscas",
  "Canelones — Libertad",
  "Canelones — Marindia",
  "Canelones — Migues",
  "Canelones — Pando",
  "Canelones — Parque del Plata",
  "Canelones — Paso Carrasco",
  "Canelones — Progreso",
  "Canelones — San Bautista",
  "Canelones — San Jacinto",
  "Canelones — San Ramón",
  "Canelones — Santa Lucía",
  "Canelones — Santa Rosa",
  "Canelones — Sauce",
  "Canelones — Shangrila",
  "Canelones — Soca",
  "Canelones — Suárez",
  "Canelones — Toledo",
  "Canelones — Tala",

  // MALDONADO
  "Maldonado — Aiguá",
  "Maldonado — El Tesoro",
  "Maldonado — Garzón",
  "Maldonado — José Ignacio",
  "Maldonado — La Barra",
  "Maldonado — Maldonado ciudad",
  "Maldonado — Pan de Azúcar",
  "Maldonado — Piriápolis",
  "Maldonado — Punta Ballena",
  "Maldonado — Punta del Este",
  "Maldonado — Punta Negra",
  "Maldonado — San Carlos",
  "Maldonado — Solanas",

  // COLONIA
  "Colonia — Carmelo",
  "Colonia — Colonia del Sacramento",
  "Colonia — Conchillas",
  "Colonia — Juan Lacaze",
  "Colonia — Florencio Sánchez",
  "Colonia — Nueva Helvecia",
  "Colonia — Nueva Palmira",
  "Colonia — Ombúes de Lavalle",
  "Colonia — Rosario",
  "Colonia — Tarariras",

  // SAN JOSÉ
  "San José — Ecilda Paullier",
  "San José — Libertad",
  "San José — Mal Abrigo",
  "San José — Rodríguez",
  "San José — San José de Mayo",
  "San José — Puntas de Valdéz",

  // FLORIDA
  "Florida — 25 de Agosto",
  "Florida — Casupá",
  "Florida — Florida ciudad",
  "Florida — Ismael Cortinas",
  "Florida — Pintado",
  "Florida — Sarandí Grande",

  // SALTO
  "Salto — Belén",
  "Salto — Constitución",
  "Salto — Colonia Lavalleja",
  "Salto — Salto ciudad",
  "Salto — San Antonio",
  "Salto — Termas del Arapey",
  "Salto — Termas de Almirón",

  // PAYSANDÚ
  "Paysandú — Chapicuy",
  "Paysandú — Guichón",
  "Paysandú — Lorenzo Geyres",
  "Paysandú — Paysandú ciudad",
  "Paysandú — Porvenir",
  "Paysandú — Quebracho",
  "Paysandú — San Félix",
  "Paysandú — Tambores",

  // RIVERA
  "Rivera — Minas de Corrales",
  "Rivera — Rivera ciudad",
  "Rivera — Tranqueras",
  "Rivera — Vichadero",

  // ROCHA
  "Rocha — Castillos",
  "Rocha — Chuy",
  "Rocha — La Paloma",
  "Rocha — La Pedrera",
  "Rocha — Lascano",
  "Rocha — Punta del Diablo",
  "Rocha — Rocha ciudad",
  "Rocha — Velázquez",

  // ARTIGAS
  "Artigas — Artigas ciudad",
  "Artigas — Bella Unión",
  "Artigas — Baltasar Brum",
  "Artigas — Tomás Gomensoro",

  // CERRO LARGO
  "Cerro Largo — Aceguá",
  "Cerro Largo — Melo",
  "Cerro Largo — Río Branco",
  "Cerro Largo — Tupambaé",

  // DURAZNO
  "Durazno — Carlos Reyles",
  "Durazno — Durazno ciudad",
  "Durazno — La Paloma",
  "Durazno — Sarandí del Yi",
  "Durazno — Villa del Carmen",

  // FLORES
  "Flores — Trinidad",
  "Flores — Ismael Cortinas",

  // LAVALLEJA
  "Lavalleja — Minas",
  "Lavalleja — José Pedro Varela",
  "Lavalleja — Pirarajá",
  "Lavalleja — Solís de Mataojo",

  // RÍO NEGRO
  "Río Negro — Fray Bentos",
  "Río Negro — Nuevo Berlín",
  "Río Negro — San Javier",
  "Río Negro — Young",

  // SORIANO
  "Soriano — Cardona",
  "Soriano — Dolores",
  "Soriano — Mercedes",
  "Soriano — Palmitas",
  "Soriano — Rodríguez",
  "Soriano — Villanueva",

  // TACUAREMBÓ
  "Tacuarembó — Ansina",
  "Tacuarembó — Paso de los Toros",
  "Tacuarembó — San Gregorio de Polanco",
  "Tacuarembó — Tacuarembó ciudad",

  // TREINTA Y TRES
  "Treinta y Tres — Treinta y Tres ciudad",
  "Treinta y Tres — Vergara",
  "Treinta y Tres — Santa Clara de Olimar",
];

export default ciudades;
